name: MineralGUI
version: 1.0.0
api: 5.0.0
author: ClickedTran
main: ClickedTran\mineral\Mineral
github: https.github.com/ClickedTran

permissions:
 mineralgui.command:
  default: true
 mineralgui.command.automine:
  default: true
