name: MineralGUI
version: 1.0.1
api: 5.0.0
author: ClickedTran
main: ClickedTran\mineral\Mineral
github: https.github.com/ClickedTran

permissions:
 mineral.command:
  default: true
 mineral.command.automine:
  default: true
 mineral.command.automine.on:
  default: true
 mineral.command.automine.off:
  default: true
